const content = {
	one: {
		rank: '#1',
		imageURL: 'img/1.png',
		title: 'The Fragile',
		artist: 'Nine Inch Nails',
		info: '1999 • 23 songs • 1:43:47',
	},
	two: {
		rank: '#2',
		imageURL: 'img/2.png',
		title: 'The Suburbs',
		artist: 'Arcade Fire',
		info: '2010 • 16 songs • 1:04:06',
	},
	three: {
		rank: '#3',
		imageURL: 'img/3.png',
		title: 'Weezer (White Album)',
		artist: 'Weezer',
		info: '2016 • 10 songs • 34:10',
	},
	four: {
		rank: '#4',
		imageURL: 'img/4.png',
		title: 'Favourite Worst Nightmare',
		artist: 'Arctic Monkeys',
		info: '2007 • 12 songs • 37:21',
	},
	five: {
		rank: '#5',
		imageURL: 'img/5.png',
		title: 'The Dark Side of the Moon',
		artist: 'Pink Floyd',
		info: '1973 • 10 songs • 42:53',
	},
	six: {
		rank: '#6',
		imageURL: 'img/6.png',
		title: 'Give Up',
		artist: 'The Postal Service',
		info: '2003 • 10 songs • 44:57',
	},
	seven: {
		rank: '#7',
		imageURL: 'img/7.png',
		title: 'Funeral',
		artist: 'Arcade Fire',
		info: '2004 • 10 songs • 48:00',
	},
	eight: {
		rank: '#8',
		imageURL: 'img/8.png',
		title: 'The Lonesome Crowded West',
		artist: 'Modest Mouse',
		info: '1997 • 15 songs • 1:13:59',
	},
	nine: {
		rank: '#9',
		imageURL: 'img/9.png',
		title: 'Icky Thump',
		artist: 'The White Stripes',
		info: '2007 • 13 songs • 48:21',
	},
	ten: {
		rank: '#10',
		imageURL: 'img/10.png',
		title: 'Since I Left You',
		artist: 'The Avalanches',
		info: '2000 • 18 songs • 1:00:39',
	},
	eleven: {
		rank: '#11',
		imageURL: 'img/11.png',
		title: 'Ladies and gentlemen we are floating in space',
		artist: 'Spiritualized',
		info: '1997 • 12 songs • 1:10:00',
	},
	twelve: {
		rank: '#12',
		imageURL: 'img/12.png',
		title: 'The Natural Bridge',
		artist: 'Silver Jews',
		info: '1996 • 10 songs • 35:45',
	},
	thirteen: {
		rank: '#13',
		imageURL: 'img/13.png',
		title: 'I\'m Wide Awake, It\'s Morning',
		artist: 'Bright Eyes',
		info: '2005 • 10 songs • 45:40',
	},
	fourteen: {
		rank: '#14',
		imageURL: 'img/14.png',
		title: 'People Who Can Eat People Are the Luckiest People in the World',
		artist: 'AJJ',
		info: '2007 • 11 songs • 25:22',
	},
	fifteen: {
		rank: '#15',
		imageURL: 'img/15.png',
		title: 'A Laughing Death in Meatspace',
		artist: 'Tropical Fuck Storm',
		info: '2018 • 9 songs • 47:17',
	},
	sixteen: {
		rank: '#16',
		imageURL: 'img/16.png',
		title: 'Bleach',
		artist: 'Nirvana',
		info: '1989 • 11 songs • 37:19',
	},
	seventeen: {
		rank: '#17',
		imageURL: 'img/17.png',
		title: '…Like Clockwork',
		artist: 'Queens of the Stone Age',
		info: '2013 • 10 songs • 46:03',
	},
	eighteen: {
		rank: '#18',
		imageURL: 'img/18.png',
		title: 'High Visceral {Part One}',
		artist: 'Psychedelic Porn Crumpets',
		info: '2016 • 10 songs • 47:09',
	},
	nineteen: {
		rank: '#19',
		imageURL: 'img/19.png',
		title: 'Sam\'s Town',
		artist: 'The Killers',
		info: '2006 • 12 songs • 44:14',
	},
	twenty: {
		rank: '#20',
		imageURL: 'img/20.png',
		title: 'American Water',
		artist: 'Silver Jews',
		info: '1998 • 12 songs • 48:21',
	},
	twentyone: {
		rank: '#21',
		imageURL: 'img/21.png',
		title: 'Mezmerize',
		artist: 'System of a Down',
		info: '2005 • 11 songs • 36:11',
	},
	twentytwo: {
		rank: '#22',
		imageURL: 'img/22.png',
		title: 'CHASER',
		artist: 'femtanyl',
		info: '2023 • 6 songs • 13:44',
	},
	twentythree: {
		rank: '#23',
		imageURL: 'img/23.png',
		title: 'Secret Treaties',
		artist: 'Blue Öyster Cult',
		info: '1974 • 8 songs • 38:24',
	},
	twentyfour: {
		rank: '#24',
		imageURL: 'img/24.png',
		title: 'Lifted',
		artist: 'Bright Eyes',
		info: '2002 • 13 songs • 1:13:31',
	},
	twentyfive: {
		rank: '#25',
		imageURL: 'img/25.png',
		title: 'Surfer Rosa',
		artist: 'Pixies',
		info: '1988 • 13 songs • 33:43',
	},
	twentysix: {
		rank: '#26',
		imageURL: 'img/26.png',
		title: 'Flying Microtonal Banana',
		artist: 'King Gizzard & the Lizard Wizard',
		info: '2017 • 9 songs • 41:56',
	},
	twentyseven: {
		rank: '#27',
		imageURL: 'img/27.png',
		title: 'Future Perfect',
		artist: 'Autolux',
		info: '2004 • 11 songs • 51:57',
	},
	twentyeight: {
		rank: '#28',
		imageURL: 'img/28.png',
		title: 'Screamadelica',
		artist: 'Primal Scream',
		info: '1991 • 11 songs • 1:02:51',
	},
	twentynine: {
		rank: '#29',
		imageURL: 'img/29.png',
		title: 'Teens of Denial',
		artist: 'Car Seat Headrest',
		info: '2016 • 12 songs • 1:10:11',
	},
	thirty: {
		rank: '#30',
		imageURL: 'img/30.png',
		title: 'Is This It',
		artist: 'The Strokes',
		info: '2001 • 11 songs • 35:48',
	},
	thirtyone: {
		rank: '#31',
		imageURL: 'img/31.png',
		title: 'Blue Öyster Cult',
		artist: 'Blue Öyster Cult',
		info: '1972 • 10 songs • 36:42',
	},
	thirtytwo: {
		rank: '#32',
		imageURL: 'img/32.png',
		title: 'Infest the Rats\' Nest',
		artist: 'King Gizzard & the Lizard Wizard',
		info: '2019 • 9 songs • 34:54',
	},
	thirtythree: {
		rank: '#33',
		imageURL: 'img/33.png',
		title: 'Definitely Maybe',
		artist: 'Oasis',
		info: '1994 • 11 songs • 52:03',
	},
	thirtyfour: {
		rank: '#34',
		imageURL: 'img/34.png',
		title: 'Daydream Nation',
		artist: 'Sonic Youth',
		info: '1988 • 12 songs • 1:10:50',
	},
	thirtyfive: {
		rank: '#35',
		imageURL: 'img/35.png',
		title: 'Everything Was Beautiful',
		artist: 'Spiritualized',
		info: '2022 • 7 songs • 44:00',
	},
	thirtysix: {
		rank: '#36',
		imageURL: 'img/36.png',
		title: 'Born to Run',
		artist: 'Bruce Springsteen',
		info: '1975 • 8 songs • 39:26',
	},
	thirtyseven: {
		rank: '#37',
		imageURL: 'img/37.png',
		title: 'We Were Dead Before the Ship Even Sank',
		artist: 'Modest Mouse',
		info: '2007 • 14 songs • 1:02:33',
	},
	thirtyeight: {
		rank: '#38',
		imageURL: 'img/38.png',
		title: 'Vol. 4',
		artist: 'Black Sabbath',
		info: '1972 • 10 songs • 42:13',
	},
	thirtynine: {
		rank: '#39',
		imageURL: 'img/39.png',
		title: 'Berlin',
		artist: 'Lou Reed',
		info: '1973 • 10 songs • 49:24',
	},
	forty: {
		rank: '#40',
		imageURL: 'img/40.png',
		title: 'Welcome to Sky Valley',
		artist: 'Kyuss',
		info: '1994 • 10 songs • 51:55',
	},
	fortyone: {
		rank: '#41',
		imageURL: 'img/41.png',
		title: 'Speaking in Tongues',
		artist: 'Talking Heads',
		info: '1983 • 9 songs • 47:10',
	},
	fortytwo: {
		rank: '#42',
		imageURL: 'img/42.png',
		title: 'Paper Mâché Dream Balloon',
		artist: 'King Gizzard & the Lizard Wizard',
		info: '2015 • 12 songs • 33:54',
	},
	fortythree: {
		rank: '#43',
		imageURL: 'img/43.png',
		title: 'How to Leave Town',
		artist: 'Car Seat Headrest',
		info: '2014 • 9 songs • 1:02:29',
	},
	fortyfour: {
		rank: '#44',
		imageURL: 'img/44.png',
		title: 'High Visceral {Part Two}',
		artist: 'Psychedelic Porn Crumpets',
		info: '2017 • 10 songs • 44:06',
	},
	fortyfive: {
		rank: '#45',
		imageURL: 'img/45.png',
		title: 'OK Human',
		artist: 'Weezer',
		info: '2021 • 12 songs • 30:38',
	},
	fortysix: {
		rank: '#46',
		imageURL: 'img/46.png',
		title: 'The Holy Bible',
		artist: 'Manic Street Preachers',
		info: '1994 • 13 songs • 56:25',
	},
	fortyseven: {
		rank: '#47',
		imageURL: 'img/47.png',
		title: 'Fresh Fruit for Rotting Vegetables',
		artist: 'Dead Kennedys',
		info: '1980 • 14 songs • 33:03',
	},
	fortyeight: {
		rank: '#48',
		imageURL: 'img/48.png',
		title: 'The Black Parade',
		artist: 'My Chemical Romance',
		info: '2006 • 14 songs • 51:57',
	},
	fortynine: {
		rank: '#49',
		imageURL: 'img/49.png',
		title: 'Eye in the Sky',
		artist: 'The Alan Parsons Project',
		info: '1982 • 10 songs • 42:29',
	},
	fifty: {
		rank: '#50',
		imageURL: 'img/50.png',
		title: 'New Wave',
		artist: 'Against Me!',
		info: '2007 • 10 songs • 33:31',
	},
	fiftyone: {
		rank: '#51',
		imageURL: 'img/51.png',
		title: 'Low',
		artist: 'David Bowie',
		info: '1977 • 11 songs • 39:04',
	},
	fiftytwo: {
		rank: '#52',
		imageURL: 'img/52.png',
		title: 'No Control',
		artist: 'Bad Religion',
		info: '1989 • 15 songs • 26:24',
	},
	fiftythree: {
		rank: '#53',
		imageURL: 'img/53.png',
		title: 'White Pepper',
		artist: 'Ween',
		info: '2000 • 12 songs • 39:32',
	},
	fiftyfour: {
		rank: '#54',
		imageURL: 'img/54.png',
		title: 'I\'m in Your Mind Fuzz',
		artist: 'King Gizzard & the Lizard Wizard',
		info: '2014 • 10 songs • 42:03',
	},
	fiftyfive: {
		rank: '#55',
		imageURL: 'img/55.png',
		title: 'The Head on the Door',
		artist: 'The Cure',
		info: '1985 • 10 songs • 37:46',
	},
	fiftysix: {
		rank: '#56',
		imageURL: 'img/56.png',
		title: 'Yankee Hotel Foxtrot',
		artist: 'Wilco',
		info: '2002 • 11 songs • 51:43',
	},
	fiftyseven: {
		rank: '#57',
		imageURL: 'img/57.png',
		title: 'Transatlanticism',
		artist: 'Death Cab for Cutie',
		info: '2003 •  11 songs • 45:43',
	},
	fiftyeight: {
		rank: '#58',
		imageURL: 'img/58.png',
		title: 'Master of Reality',
		artist: 'Black Sabbath',
		info: '1973 • 8 songs • 34:24',
	},
	fiftynine: {
		rank: '#59',
		imageURL: 'img/59.png',
		title: 'The Stone Roses',
		artist: 'The Stone Roses',
		info: '1989 • 12 songs • 58:43',
	},
	sixty: {
		rank: '#60',
		imageURL: 'img/60.png',
		title: 'Disintegration',
		artist: 'The Cure',
		info: '1989 • 12 songs • 1:12:16',
	},
	sixtyone: {
		rank: '#61',
		imageURL: 'img/61.png',
		title: 'Three Cheers for Sweet Revenge',
		artist: 'My Chemical Romance',
		info: '2004 • 13 songs • 39:33',
	},
	sixtytwo: {
		rank: '#62',
		imageURL: 'img/62.png',
		title: 'Darklands',
		artist: 'The Jesus and Mary Chain',
		info: '1987 • 10 songs • 36:08',
	},
	sixtythree: {
		rank: '#63',
		imageURL: 'img/63.png',
		title: 'Time',
		artist: 'Electric Light Orchestra',
		info: '1981 • 13 songs • 44:00',
	},
	sixtyfour: {
		rank: '#64',
		imageURL: 'img/64.png',
		title: 'Quebec',
		artist: 'Ween',
		info: '2003 • 15 songs • 55:03',
	},
	sixtyfive: {
		rank: '#65',
		imageURL: 'img/65.png',
		title: 'With Teeth',
		artist: 'Nine Inch Nails',
		info: '2005 • 13 songs • 56:06',
	},
	sixtysix: {
		rank: '#66',
		imageURL: 'img/66.png',
		title: 'Low-Life',
		artist: 'New Order',
		info: '1985 • 8 songs • 40:07',
	},
	sixtyseven: {
		rank: '#67',
		imageURL: 'img/67.png',
		title: 'Spiderland',
		artist: 'Slint',
		info: '1991 • 6 songs • 39:33',
	},
	sixtyeight: {
		rank: '#68',
		imageURL: 'img/68.png',
		title: 'Mount Eerie',
		artist: 'The Microphones',
		info: '2003 • 5 songs • 40:53',
	},
	sixtynine: {
		rank: '#69',
		imageURL: 'img/69.png',
		title: 'Transgender Dysphoria Blues',
		artist: 'Against Me!',
		info: '2014 • 10 songs • 28:46',
	},
	seventy: {
		rank: '#70',
		imageURL: 'img/70.png',
		title: 'Whatever People Say I Am, That\'s What I\'m Not',
		artist: 'Arctic Monkeys',
		info: '2006 • 13 songs • 41:09',
	},
	seventyone: {
		rank: '#71',
		imageURL: 'img/71.png',
		title: 'Violator',
		artist: 'Depeche Mode',
		info: '1990 • 9 songs • 46:55',
	},
	seventytwo: {
		rank: '#72',
		imageURL: 'img/72.png',
		title: 'Transformer',
		artist: 'Lou Reed',
		info: '1972 • 11 songs • 37:04',
	},
	seventythree: {
		rank: '#73',
		imageURL: 'img/73.png',
		title: 'The Sufferer & the Witness',
		artist: 'Rise Against',
		info: '2006 • 13 songs • 41:41',
	},
	seventyfour: {
		rank: '#74',
		imageURL: 'img/74.png',
		title: 'Darkness on the Edge of Town',
		artist: 'Bruce Springsteen',
		info: '1978 • 10 songs • 42:59',
	},
	seventyfive: {
		rank: '#75',
		imageURL: 'img/75.png',
		title: 'Wish You Were Here',
		artist: 'Pink Floyd',
		info: '1975 • 5 songs • 44:12',
	},
	seventysix: {
		rank: '#76',
		imageURL: 'img/76.png',
		title: 'Sound of Silver',
		artist: 'LCD Soundsystem',
		info: '2007 • 9 songs • 56:12',
	},
	seventyseven: {
		rank: '#77',
		imageURL: 'img/77.png',
		title: 'viagr aboys',
		artist: 'Viagra Boys',
		info: '2025 • 11 songs • 37:22',
	},
	seventyeight: {
		rank: '#78',
		imageURL: 'img/78.png',
		title: 'Origin of Symmetry',
		artist: 'Muse',
		info: '2001 • 11 songs • 51:41',
	},
	seventynine: {
		rank: '#79',
		imageURL: 'img/79.png',
		title: 'Let it come down',
		artist: 'Spiritualized',
		info: '2001 • 11 songs • 1:02:50',
	},
	eighty: {
		rank: '#80',
		imageURL: 'img/80.png',
		title: 'Fear of Music',
		artist: 'Talking Heads',
		info: '1979 • 11 songs • 40:40',
	},
	eightyone: {
		rank: '#81',
		imageURL: 'img/81.png',
		title: 'PetroDragonic Apocalypse',
		artist: 'King Gizzard & the Lizard Wizard',
		info: '2023 • 7 songs • 48:40',
	},
	eightytwo: {
		rank: '#82',
		imageURL: 'img/82.png',
		title: 'Ixnay on the Hombre',
		artist: 'The Offspring',
		info: '1997 • 14 songs • 42:24',
	},
	eightythree: {
		rank: '#83',
		imageURL: 'img/83.png',
		title: 'Year Zero',
		artist: 'Nine Inch Nails',
		info: '2007 • 15 songs • 1:03:43',
	},
	eightyfour: {
		rank: '#84',
		imageURL: 'img/84.png',
		title: 'Bossanova',
		artist: 'Pixies',
		info: '1990 • 14 songs • 39:45',
	},
	eightyfive: {
		rank: '#85',
		imageURL: 'img/85.png',
		title: '21st Century Breakdown',
		artist: 'Green Day',
		info: '2009 • 18 songs • 1:09:16',
	},
	eightysix: {
		rank: '#86',
		imageURL: 'img/86.png',
		title: 'The Soft Bulletin',
		artist: 'The Flaming Lips',
		info: '1999 • 12 songs • 50:00',
	},
	eightyseven: {
		rank: '#87',
		imageURL: 'img/87.png',
		title: 'The Land of Rape and Honey',
		artist: 'Ministry',
		info: '1986 • 9 songs • 40:25',
	},
	eightyeight: {
		rank: '#88',
		imageURL: 'img/88.png',
		title: 'Room on Fire',
		artist: 'The Strokes',
		info: '2003 • 11 songs • 33:05',
	},
	eightynine: {
		rank: '#89',
		imageURL: 'img/89.png',
		title: 'A Flock of Seagulls',
		artist: 'A Flock of Seagulls',
		info: '1982 • 10 songs • 38:16',
	},
	ninety: {
		rank: '#90',
		imageURL: 'img/90.png',
		title: 'Repetition',
		artist: 'Unwound',
		info: '1996 • 12 songs • 46:18',
	},
	ninetyone: {
		rank: '#91',
		imageURL: 'img/91.png',
		title: 'Discovery',
		artist: 'Electric Light Orchestra',
		info: '1979 • 9 songs • 38:50',
	},
	ninetytwo: {
		rank: '#92',
		imageURL: 'img/92.png',
		title: 'My Dinosaur Life',
		artist: 'Motion City Soundtrack',
		info: '2010 • 12 songs • 39:56',
	},
	ninetythree: {
		rank: '#93',
		imageURL: 'img/93.png',
		title: 'Good News for People Who Love Bad News',
		artist: 'Modest Mouse',
		info: '2004 • 16 songs • 48:39',
	},
	ninetyfour: {
		rank: '#94',
		imageURL: 'img/94.png',
		title: 'Nonagon Infinity',
		artist: 'King Gizzard & the Lizard Wizard',
		info: '2016 • 10 songs • 41:48',
	},
	ninetyfive: {
		rank: '#95',
		imageURL: 'img/95.png',
		title: 'The Downward Spiral',
		artist: 'Nine Inch Nails',
		info: '1994 • 14 songs • 1:05:07',
	},
	ninetysix: {
		rank: '#96',
		imageURL: 'img/96.png',
		title: 'Trans Europa Express',
		artist: 'Kraftwerk',
		info: '1977 • 8 songs • 42:57',
	},
	ninetyseven: {
		rank: '#97',
		imageURL: 'img/97.png',
		title: 'Toxicity',
		artist: 'System of a Down',
		info: '2001 • 14 songs • 44:01',
	},
	ninetyeight: {
		rank: '#98',
		imageURL: 'img/98.png',
		title: 'The Moon & Antarctica',
		artist: 'Modest Mouse',
		info: '2000 • 15 songs • 58:45',
	},
	ninetynine: {
		rank: '#99',
		imageURL: 'img/99.png',
		title: 'Eliminator',
		artist: 'ZZ Top',
		info: '1983 • 11 songs • 45:28',
	},
	hundred: {
		rank: '#100',
		imageURL: 'img/100.png',
		title: 'Hesitation Marks',
		artist: 'Nine Inch Nails',
		info: '2013 • 14 songs • 1:01:59',
	},
};

function showInfo(clickedId) {
	const noneSelected = document.getElementById('noneselected');
	const coverImage = document.getElementById('cover-image');
	const rank = document.getElementById('rank');
	const albumTitle = document.getElementById('title');
	const artist = document.getElementById('artist');
	const moreInfo = document.getElementById('info');

	noneSelected.style.display = "none";
	rank.textContent = content[clickedId].rank;
	albumTitle.textContent = content[clickedId].title;
	artist.textContent = content[clickedId].artist;
	moreInfo.textContent = content[clickedId].info;

	document.getElementById("none").style.display = "none";
	coverImage.src = content[clickedId].imageURL;
	coverImage.style.display = 'block';
}